name: 'Release'

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: run
          args: --release --all-features
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: unpacked-hay-block
          path: out/*.png
      - name: Update release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: out/*.zip
          asset_name: mything
          file_glob: true
          overwrite: true
          body: "This is my release text"