name: 'Release'

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: run
          args: --release --all-features
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: unpacked-hay-block
          path: out/*.png
      - name: Update release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: 'latest'
          file: out/*.zip
          file_glob: true
          overwrite: true
          body: "Free your hay blocks! 32x and 64x resource pack add-on"